### PR TITLE
PR to fix issues, and have bridge survive reboots

### PR DESCRIPTION
**Pull request by KelvinTegelaar**

### CODE REVIEW

**Comment by KelvinTegelaar** [comment]
There are some limitations to the caching: It only loads after the bridge has been up for 10 seconds due to the way its designed, and it is always at least 10 seconds of messages behind. It's a good first start though.

**Review by mspgeek-community — APPROVED** [review]
I like it

**Review by mspgeek-community — APPROVED** [review]
thanks

**Review by mspgeek-community — APPROVED** [review]
I'm curious why we need "+ broadcastmsg.Text" still at the end of line 145, or if it was carry over. Approving and we can confirm.

**Review by mspgeek-community — APPROVED** [review]
you so smaht

**Pull request merged**
